const ADD_NICKNAME = 'ADD_NICKNAME';
const GET_DATA ='GET_DATA';
const GET_ID = 'GET_ID';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const POST_DOGS = 'POST_DOGS';
const RESET_MESSAGE ='RESET_MESSAGE';
const SEARCH_DOG = 'SEARCH_DOG';
const FILTER_AZ = 'FILTER_AZ';
const FILTER_ZA ='FILTER_ZA';
const FILTER_WEIGHT = 'FILTER_WEIGHT';
const FILTER_API = 'FILTER_API';
const FILTER_TEMP = 'FILTER_TEMP';
const CHANGE_PAGE = 'CHANGE_PAGE';
const CHANGE_PAGE_SEARCH = 'CHANGE_PAGE_SEARCH';

module.exports = {
    ADD_NICKNAME,
    GET_DATA,
    GET_ID,
    GET_TEMPERAMENTS,
    POST_DOGS,
    RESET_MESSAGE,
    SEARCH_DOG,
    FILTER_AZ,
    FILTER_ZA,
    FILTER_WEIGHT,
    FILTER_API,
    FILTER_TEMP,
    CHANGE_PAGE,
    CHANGE_PAGE_SEARCH 
   
    
}