const ADD_NICKNAME = 'ADD_NICKNAME';
const GET_DATA ='GET_DATA';
const GET_ID = 'GET_ID';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const POST_DOGS = 'POST_DOGS';
const RESET_MESSAGE ='RESET_MESSAGE';
const SEARCH_DOG = 'SEARCH_DOG';
module.exports = {
    ADD_NICKNAME,
    GET_DATA,
    GET_ID,
    GET_TEMPERAMENTS,
    POST_DOGS,
    RESET_MESSAGE,
    SEARCH_DOG
}